// <auto-generated />
namespace AuctionSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Auction_EndingTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Auction_EndingTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202112181702387_Auction_EndingTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
